// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace TextOn.Studio
{
	public partial class CreateTemplateViewController : NSViewController
	{
		public CreateTemplateViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad ()
        {
            base.ViewDidLoad ();

            // Set up the view with useful titles and description.
            Title = TitleText;
            TitleLabel.StringValue = TitleText;
            DescriptionLabel.StringValue = DescriptionText;
        }

        /// <summary>
        /// Gets or sets the title text.
        /// </summary>
        /// <value>The title text.</value>
        public string TitleText { get; set; }

        /// <summary>
        /// Gets or sets the description text.
        /// </summary>
        /// <value>The description text.</value>
        public string DescriptionText { get; set; }

        /// <summary>
        /// Gets the user's sample text to insert into the template.
        /// </summary>
        /// <value>The sample text.</value>
        public string SampleText {
            get {
                return TextView.Value;
            }
        }

        public NSViewController Presentor { get; set; }

        private void CloseDialog ()
        {
            Presentor.DismissViewController (this);
        }

        partial void Cancel_Clicked (Foundation.NSObject sender)
        {
            CloseDialog ();
        }

        partial void OK_Clicked (Foundation.NSObject sender)
        {
            RaiseDialogAccepted ();
            CloseDialog ();
        }

        public EventHandler DialogAccepted;

        internal void RaiseDialogAccepted ()
        {
            if (this.DialogAccepted != null)
                this.DialogAccepted (this, EventArgs.Empty);
        }
	}
}
