// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using CoreGraphics;

namespace TextOn.Studio
{
	public partial class DefineNounsViewController : NSViewController
	{
		public DefineNounsViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad ()
        {
            base.ViewDidLoad ();
        }

        bool apparent = false;

        public override void ViewDidAppear ()
        {
            base.ViewDidAppear ();

            var datasource = new DefineNounsTableViewDataSource (centralViewController.Template.Nouns);
            DefineNounsTableView.DataSource = datasource;
            DefineNounsTableView.Delegate = new DefineNounsTableViewDelegate (datasource);
            apparent = true;
        }

        public override void ViewDidDisappear ()
        {
            base.ViewDidDisappear ();
            DefineNounsTableView.DataSource = null;
            DefineNounsTableView.Delegate = null;
            apparent = false;
        }

        internal void TemplateUpdated ()
        {
            if (apparent) {
                var datasource = new DefineNounsTableViewDataSource (centralViewController.Template.Nouns);
                DefineNounsTableView.DataSource = datasource;
                DefineNounsTableView.Delegate = new DefineNounsTableViewDelegate (datasource);
            }
        }

        private CentralViewController centralViewController = null;
        internal void SetControllerLinks (CentralViewController cvc)
        {
            Console.Error.WriteLine ("DefineNouns SetControllerLinks");
            centralViewController = cvc;
        }

   }
}
