// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using CoreGraphics;
using System.Collections.Generic;

namespace TextOn.Studio
{
    public partial class DefineNounsViewController : NSViewController
    {
        public DefineNounsViewController (IntPtr handle) : base (handle)
        {
        }

        public override void ViewDidLoad ()
        {
            base.ViewDidLoad ();
        }

        bool apparent = false;

        public override void ViewDidAppear ()
        {
            base.ViewDidAppear ();

            var datasource = new DefineNounsTableViewDataSource (centralViewController.Template.Nouns);
            DefineNounsTableView.DataSource = datasource;
            DefineNounsTableView.Delegate = new DefineNounsTableViewDelegate (this, datasource);
            apparent = true;
        }

        public override void ViewDidDisappear ()
        {
            base.ViewDidDisappear ();
            DefineNounsTableView.DataSource = null;
            DefineNounsTableView.Delegate = null;
            apparent = false;
        }

        internal void TemplateUpdated ()
        {
            if (apparent) {
                var datasource = new DefineNounsTableViewDataSource (centralViewController.Template.Nouns);
                DefineNounsTableView.DataSource = datasource;
                DefineNounsTableView.Delegate = new DefineNounsTableViewDelegate (this, datasource);
            }
        }

        private CentralViewController centralViewController = null;
        internal void SetControllerLinks (CentralViewController cvc)
        {
            Console.Error.WriteLine ("DefineNouns SetControllerLinks");
            centralViewController = cvc;
        }

        public override void PrepareForSegue (NSStoryboardSegue segue, NSObject sender)
        {
            base.PrepareForSegue (segue, sender);

            switch (segue.Identifier) {
            case DesignViewDialogSegues.AddNewNoun:
                var dlg = segue.DestinationController as AddNewNounViewController;
                dlg.Presentor = this;
                dlg.DialogAccepted += (s, e) => {
                    centralViewController.Template.Nouns.AddNewNoun (dlg.NameText, dlg.DescriptionText, dlg.AcceptsUserValue);
                    TemplateUpdated ();
                };
                break;
            case DesignViewDialogSegues.DeleteSuggestion:
                var ddlg = segue.DestinationController as DeleteSuggestionViewController;
                ddlg.Presentor = this;
                ddlg.NounName = nounNameToDelete;
                ddlg.SuggestionValue = suggestionValueToDelete;
                ddlg.DialogAccepted += (s, e) => {
                    centralViewController.Template.Nouns.DeleteSuggestion (nounNameToDelete, suggestionValueToDelete);
                };
                break;
            default:
                break;
            }
        }

        private string nounNameToDelete;
        private string suggestionValueToDelete;
        public void DeleteSuggestion (string nounName, string suggestionValue)
        {
            nounNameToDelete = nounName;
            suggestionValueToDelete = suggestionValue;
            PerformSegue (DesignViewDialogSegues.DeleteSuggestion, this);
        }
    }
}
