// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace TextOn.Studio
{
	public partial class DesignPreviewTextView : NSTextView
	{
		public DesignPreviewTextView (IntPtr handle) : base (handle)
		{
		}
	}
}
