// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Linq;
using Foundation;
using AppKit;
using System.Collections.Generic;
using TextOn.Compiler;

namespace TextOn.Studio
{
	public partial class SetVariablesViewController : NSViewController
	{
		public SetVariablesViewController (IntPtr handle) : base (handle)
		{
		}

        public IReadOnlyDictionary<string, string> VariableValues {
            get {
                if (this.SetVariables.DataSource == null) return new Dictionary<string, string> ();
                return ((VariablesTableViewDataSource)SetVariables.DataSource).VariableValues;
            }
        }

        private CentralViewController parent = null;
        internal void SetControllerLinks (CentralViewController centralViewController)
        {
            Console.Error.WriteLine ("SetVariables SetControllerLinks");

            this.parent = centralViewController;   
        }

        internal void SetCompiledTemplate ()
        {
            Console.Error.WriteLine ("SetVariables SetCompiledTemplate");

            var datasource = new VariablesTableViewDataSource (parent.CompiledTemplate.Nouns);
            SetVariables.DataSource = datasource;
            SetVariables.Delegate = new VariablesTableViewDelegate (datasource);
        }
	}
}
