// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace TextOn.Studio
{
	public partial class TextOnWindowController : NSWindowController
	{
		public TextOnWindowController (IntPtr handle) : base (handle)
		{
		}

        /// <summary>
        /// Signals to view controllers that the user is creating a new document.
        /// </summary>
        public bool IsInNew { get; set; } = false;

        [Action ("search:")]
        public void SearchText (NSObject sender)
        {
            var centralViewController = this.ContentViewController as CentralViewController;
            centralViewController.Search ();
        }
    }
}
