// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace TextOn.Studio
{
	public partial class TextOnWindowController : NSWindowController
	{
		public TextOnWindowController (IntPtr handle) : base (handle)
		{
		}

        /// <summary>
        /// Signals to view controllers that the user is creating a new document.
        /// </summary>
        internal bool IsInNew = false;
	}
}
