// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace Skrivmaskin.Editor
{
	public partial class EditDialogController : NSViewController
	{
		public EditDialogController (IntPtr handle) : base (handle)
		{
		}

        string editTitleText;
        public string EditTitleText {
            [Export ("editTitleText")]
            get {
                return editTitleText;
            }
            set {
                editTitleText = value;
            }
        }

        string newDetailsText;
        public string NewDetailsText {
            [Export ("newDetailsText")]
            get {
                return newDetailsText;
            }
            set {
                newDetailsText = value;
            }
        }

        public string NewDetailsOutput { get { return NewDetails.Value; } }

        public NSViewController Presentor { get; set; }

        private void CloseDialog ()
        {
            Presentor.DismissViewController (this);
        }

        partial void Cancel_Pressed (Foundation.NSObject sender)
        {
            CloseDialog ();
        }

        partial void OK_Pressed (Foundation.NSObject sender)
        {
            RaiseDialogAccepted ();
            CloseDialog ();
        }

        public EventHandler DialogAccepted;

        internal void RaiseDialogAccepted ()
        {
            if (this.DialogAccepted != null)
                this.DialogAccepted (this, EventArgs.Empty);
        }
	}
}
