// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace Skrivmaskin.Editor
{
	public partial class GeneralPurposeDialogController : NSViewController
	{
		public GeneralPurposeDialogController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad ()
        {
            base.ViewDidLoad ();
            Title = dialogTitle;
            NameText.StringValue = NameTextInput;
            DetailsText.StringValue = DetailsTextInput;
            SuggestionText.StringValue = SuggestionTextInput;
        }

        string dialogTitle;
        public string DialogTitle {
            [Export ("dialogTitle")]
            get {
                return dialogTitle;
            }
            set {
                dialogTitle = value;
            }
        }

        string dialogMessage;
        public string DialogMessage {
            [Export ("dialogMessage")]
            get {
                return dialogMessage;
            }
            set {
                dialogMessage = value;
            }
        }

        string nameLabelInput;
        public string NameLabelInput {
            [Export ("nameLabelInput")]
            get {
                return nameLabelInput;
            }
            set {
                nameLabelInput = value;
            }
        }

        string detailsLabelInput;
        public string DetailsLabelInput {
            [Export ("detailsLabelInput")]
            get {
                return detailsLabelInput;
            }
            set {
                detailsLabelInput = value;
            }
        }

        public string NameTextInput { get; set; } = "";

        public string DetailsTextInput { get; set; } = "";

        public string SuggestionTextInput { get; set; } = "";

        public string NameTextOutput { get { return NameText.StringValue; } }
        public string DetailsTextOutput { get { return DetailsText.StringValue; } }
        public string SuggestionTextOutput { get { return SuggestionText.StringValue; } }

        bool _showNameEditField = true;
        public bool showNameEditField {
            [Export ("showNameEditField")]
            get {
                return _showNameEditField;
            }
            set { _showNameEditField = value;}
        }

        bool _showDetailsEditField;
        public bool showDetailsEditField {
            [Export ("showDetailsEditField")]
            get {
                return _showDetailsEditField;
            }
            set { _showDetailsEditField = value;}
        }

        bool _showSuggestionEditField;
        public bool showSuggestionEditField {
            [Export ("showSuggestionEditField")]
            get {
                return _showSuggestionEditField;
            }
            set { _showSuggestionEditField = value; }
        }

        bool _showActive;
        public bool showActive {
            [Export ("showActive")]
            get {
                return _showActive;
            }
            set {
                _showActive = value;
            }
        }

        public NSViewController Presentor { get; set; }

        private void CloseDialog ()
        {
            Presentor.DismissViewController (this);
        }

        partial void Cancel_Clicked (Foundation.NSObject sender)
        {
            CloseDialog ();
        }

        partial void OK_Clicked (Foundation.NSObject sender)
        {
            RaiseDialogAccepted ();
            CloseDialog ();
        }

        public EventHandler DialogAccepted;

        internal void RaiseDialogAccepted ()
        {
            if (this.DialogAccepted != null)
                this.DialogAccepted (this, EventArgs.Empty);
        }
	}
}
