// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace Skrivmaskin.Editor
{
	public partial class NewVariableDialogController : NSViewController
	{
		public NewVariableDialogController (IntPtr handle) : base (handle)
		{
		}

        public string NewVariableDescription { get { return VariableDescription.StringValue; } }

        public string NewVariableName { get { return VariableName.StringValue; } }

        public string NewVariableSuggestion { get { return VariableSuggestion.StringValue; } }

        public NSViewController Presentor { get; set; }

        private void CloseDialog ()
        {
            Presentor.DismissViewController (this);
        }

        partial void Cancel_Pressed (Foundation.NSObject sender)
        {
            CloseDialog ();
        }

        partial void OK_Pressed (Foundation.NSObject sender)
        {
            RaiseDialogAccepted ();
            CloseDialog ();
        }

        public EventHandler DialogAccepted;

        internal void RaiseDialogAccepted ()
        {
            if (this.DialogAccepted != null)
                this.DialogAccepted (this, EventArgs.Empty);
        }
	}
}
