// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace Skrivmaskin.Editor
{
	public partial class NewVariableVariantDialogController : NSViewController
	{
		public NewVariableVariantDialogController (IntPtr handle) : base (handle)
		{
		}

        public string NewVariableVariantNameText { get { return NewVariableVariantName.StringValue; } }

        public string NewVariableVariantSuggestionText { get { return NewVariableVariantSuggestion.StringValue; } }

        public NSViewController Presentor { get; set; }

        private void CloseDialog ()
        {
            Presentor.DismissViewController (this);
        }

        partial void Cancel_Pressed (Foundation.NSObject sender)
        {
            CloseDialog ();
        }

        partial void OK_Pressed (Foundation.NSObject sender)
        {
            RaiseDialogAccepted ();
            CloseDialog ();
        }

        public EventHandler DialogAccepted;

        internal void RaiseDialogAccepted ()
        {
            if (this.DialogAccepted != null)
                this.DialogAccepted (this, EventArgs.Empty);
        }
	}
}
