// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace Skrivmaskin.Editor
{
	public partial class RenameDialogController : NSViewController
	{
		public RenameDialogController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewWillAppear ()
        {
            base.ViewWillAppear ();

            // Set initial title and description
            RenameTitle.StringValue = RenameDialogTitle;
        }

        public string RenameDialogTitle { get; set; } = "";

        public string NewNameValue {
            get {
                return NewName.StringValue;
            }
        }

        public NSViewController Presentor { get; set; }

        private void CloseDialog ()
        {
            Presentor.DismissViewController (this);
        }

        partial void Cancel_Pressed (Foundation.NSObject sender)
        {
            CloseDialog ();
        }

        partial void OK_Pressed (Foundation.NSObject sender)
        {
            RaiseDialogAccepted ();
            CloseDialog ();
        }

        public EventHandler DialogAccepted;

        internal void RaiseDialogAccepted ()
        {
            if (this.DialogAccepted != null)
                this.DialogAccepted (this, EventArgs.Empty);
        }
	}
}
