// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Linq;
using Foundation;
using AppKit;
using Skrivmaskin.Compiler;
using Skrivmaskin.Interfaces;
using Skrivmaskin.Generation;
using Skrivmaskin.Services;
using System.Collections.Generic;

namespace Skrivmaskin.Editor
{
    public partial class RunViewController : NSViewController
    {
        private CompiledProject compiledProject = null;

        public RunViewController (IntPtr handle) : base (handle)
        {
        }

        internal void SetCompiledProject (CompiledProject c)
        {
            compiledProject = c;
            var datasource = new SkrivmaskinVariablesTableViewDataSource (c.VariableDefinitions.Select ((kvp) => kvp.Value));
            Variables.DataSource = datasource;
            Variables.Delegate = new SkrivmaskinVariablesTableViewDelegate (datasource);
        }

        internal CompiledProject GetCompiledProject ()
        {
            return compiledProject;
        }

        public IReadOnlyDictionary<string, string> VariableValues {
            get {
                if (Variables.DataSource == null) return new Dictionary<string, string> ();
                return ((SkrivmaskinVariablesTableViewDataSource)Variables.DataSource).VariableValues;
            }
        }

        internal void SetResults (string results)
        {
            Results.Value = results;
        }

        partial void GenerateClicked (Foundation.NSObject sender)
        {
            Generate ();
        }

        readonly SkrivmaskinGenerator generator = new SkrivmaskinGenerator (new RandomChooser (), new SingleSpaceUnixGeneratorConfig ());

        public void Generate ()
        {
            if (compiledProject != null) {
                var text = (generator.Generate (compiledProject, new DictionaryBackedVariableSubstituter (VariableValues)));
                Results.Value = text;
            } else {
                Results.Value = "Nothing to generate";
            }
        }

        public override void ViewDidLoad ()
        {
            base.ViewDidLoad ();

            // Set the initial value for the label
            Results.Value = "No results generated yet.";
        }
    }
}
