// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace Skrivmaskin.Editor
{
	public partial class RunViewController : NSViewController
    {
		public RunViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
