// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace Skrivmaskin.Editor
{
	public partial class TabViewController : NSTabViewController
    {
        public string FilePath { get; set; } = null;

		public TabViewController (IntPtr handle) : base (handle)
		{
		}


	}
}
