// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace Skrivmaskin.Studio
{
	public partial class CreateTemplateDialogController : NSViewController
	{
		public CreateTemplateDialogController (IntPtr handle) : base (handle)
		{
		}
	}
}
