// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace Skrivmaskin.Studio
{
	public partial class DesignTreeController : NSTreeController
	{
		public DesignTreeController (IntPtr handle) : base (handle)
		{
		}

        public override bool CanAddChild {
            get {
                if (SelectedObjects.Length != 1) return false;
                var model = (DesignModel)SelectedObjects [0];
                return model.modelType != DesignModelType.Text && model.modelType != DesignModelType.VariableForm;
            }
        }
	}
}
