// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using Skrivmaskin.Generation;
using Skrivmaskin.Services;
using System.Collections.Generic;
using Skrivmaskin.Compiler;
using Skrivmaskin.Design;

namespace Skrivmaskin.Studio
{
    public partial class ResultsViewController : NSViewController
    {
        public ResultsViewController (IntPtr handle) : base (handle)
        {
        }

        public override void ViewDidLoad ()
        {
            base.ViewDidLoad ();

            // Set the initial value for the label
            ResultsView.Output = null;

            // Listen to modified clicks from the user.
            ResultsView.ModifiedClick += OnModifiedClick;
        }

        void OnModifiedClick (INode designNode)
        {
            if (parent != null) {
                parent.NavigateAndSelectDesignNode (designNode);
            }
        }

        partial void Generate_Clicked (Foundation.NSObject sender)
        {
            Generate ();
        }

        private CentralViewController parent = null;
        internal void SetControllerLinks (CentralViewController cvc)
        {
            parent = cvc;
        }

        readonly SkrivmaskinGenerator generator = new SkrivmaskinGenerator (new RandomChooser (), new SingleSpaceUnixGeneratorConfig ());

        public void Generate ()
        {
            if (parent.CompiledProject != null) {
                ResultsView.Output = (generator.Generate (parent.CompiledProject, new DictionaryBackedVariableSubstituter (parent.VariableValues)));
            } else {
                ResultsView.Output = null;
            }
        }
    }
}
