// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using Skrivmaskin.Generation;
using Skrivmaskin.Services;
using System.Collections.Generic;
using Skrivmaskin.Compiler;

namespace Skrivmaskin.Studio
{
    public partial class ResultsViewController : NSViewController
    {
        public ResultsViewController (IntPtr handle) : base (handle)
        {
        }

        public override void ViewDidLoad ()
        {
            base.ViewDidLoad ();

            // Set the initial value for the label
            Results.Value = "No results generated yet.";
        }

        partial void Generate_Clicked (Foundation.NSObject sender)
        {
            Generate ();
        }

        private CompiledProject compiledProject = null;
        IReadOnlyDictionary<string, string> variableValues = null;

        internal void SetCompiledProject (IReadOnlyDictionary<string, string> vv, CompiledProject c)
        {
            compiledProject = c;
            variableValues = vv;
        }

        readonly SkrivmaskinGenerator generator = new SkrivmaskinGenerator (new RandomChooser (), new SingleSpaceUnixGeneratorConfig ());

        public void Generate ()
        {
            if (compiledProject != null) {
                Results.Value = (generator.Generate (compiledProject, new DictionaryBackedVariableSubstituter (variableValues)));
            } else {
                Results.Value = "Nothing to generate";
            }
        }

    }
}
