// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Linq;
using Foundation;
using AppKit;
using System.Collections.Generic;
using Skrivmaskin.Compiler;

namespace Skrivmaskin.Studio
{
	public partial class SetVariablesViewController : NSViewController
	{
		public SetVariablesViewController (IntPtr handle) : base (handle)
		{
		}

        public IReadOnlyDictionary<string, string> VariableValues {
            get {
                if (this.SetVariables.DataSource == null) return new Dictionary<string, string> ();
                return ((VariablesTableViewDataSource)SetVariables.DataSource).VariableValues;
            }
        }

        private CentralViewController parent = null;
        internal void SetControllerLinks (CentralViewController centralViewController)
        {
            this.parent = centralViewController;   
        }

        internal void SetCompiledProject ()
        {
            var datasource = new VariablesTableViewDataSource (parent.CompiledProject.VariableDefinitions.Select ((kvp) => kvp.Value));
            SetVariables.DataSource = datasource;
            SetVariables.Delegate = new VariablesTableViewDelegate (datasource);
        }
	}
}
