// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using Skrivmaskin.Design;
using System.Collections.Generic;

namespace Skrivmaskin.Studio
{
	public partial class TestBedViewController : NSViewController
	{
		public TestBedViewController (IntPtr handle) : base (handle)
		{
            
		}
    }
}
